### ISSUE TITLE
Practica Diagrama de Clases

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-equipo-exe#1]
[Diagrama de clases Oaxaqueando.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-equipo-exe/files/7824373/Diagrama.de.clases.Oaxaqueando.pdf)

**Comment by KarlaV0** [comment]
30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
